name: Build

on:
  watch:
    types: [started]
  push:
    paths:
      - '**.cs'
      - '**.yml'
  pull_request:

jobs:
    draft_release:
      outputs:
        tag_name:  ${{ steps.Draft.outputs.tag_name }}
      name: Draft release
      runs-on: ubuntu-latest
      steps:
        - uses: release-drafter/release-drafter@v5
          id: Draft
          name: Draft
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    Format:
      runs-on: windows-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Format
        run: dotnet-format  ${{ github.workspace }}\CokeeDP.sln

      - name: Commit and Push
        shell: bash
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "action@github.com"
          git add -u
          git commit -m "style: Automated dotnet-format update from commit ${GITHUB_SHA} on ${GITHUB_REF}"
          git log -1
          remote_repo="https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${remote_repo}" HEAD:${GITHUB_REF}
        continue-on-error: true

    Build:
      needs: [draft_release]
      runs-on: windows-latest
      strategy:
        matrix:
          project: [WPF]
      steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'
          
      - name: Write Build info
        shell: cmd
        run: |
            cmd /c echo GITHUB ACTION #${{github.run_number}} >${{ github.workspace }}\Build_Info.txt
            cmd /c echo %date% %time% >>${{ github.workspace }}\Build_Info.txt
            cmd /c echo %cd% >>${{ github.workspace }}\Build_Info.txt
            cmd /c echo %os% >>${{ github.workspace }}\Build_Info.txt
            cmd /c echo ${{github.ref}} ${{github.sha}}>>${{ github.workspace }}\Build_Info.txt
      - name: NuGet restore
        run: nuget restore ${{ github.workspace }}\CokeeDP.csproj

      - name: Build the project(Release)
        run: msbuild -p:Configuration=Release ${{ github.workspace }\CokeeDP}.csproj

      - name: Build the project(Debug)
        run: msbuild -p:Configuration=Debug ${{ github.workspace }\CokeeDP.csproj

      - name: Upload CokeeDP(Release,dotnet6)
        uses: actions/upload-artifact@v3
        with:
          name: CokeeDP_${{ needs.draft_release.outputs.tag_name }}_dotnet6
          path: ${{ github.workspace }}\bin\Release\net6.0-windows10.0.22000.0

      - name: Upload CokeeDP(Debug,dotnet6)
        uses: actions/upload-artifact@v3
        with:
          name: CokeeDP_${{ needs.draft_release.outputs.tag_name }}_dotnet6_debug
          path: ${{ github.workspace }}\bin\Debug\net6.0-windows10.0.22000.0
